from dataclasses import dataclass


@dataclass
class UIChecklistItem:
    id: str
    page_type: str
    name: str
    priority: str       # mandatory | high | nicetohave
    check_mode: str     # auto | manual | screenshot
    crawl_field: str | None   # field name in crawl_page result (if auto)
    manual_guide: str | None  # how-to instructions (if manual or screenshot)
    vision_prompt: str | None = None  # prompt Claude uses when user shares a screenshot


UI_CHECKLIST: list[UIChecklistItem] = [
    # =========================================================
    # HEADER (9 items — appears on every page)
    # =========================================================
    UIChecklistItem(
        id="header_01",
        page_type="header",
        name="Logo hiển thị góc trên bên trái, click về trang chủ",
        priority="mandatory",
        check_mode="auto",
        crawl_field="header_has_logo",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="header_02",
        page_type="header",
        name="Menu điều hướng chính hiển thị rõ ràng",
        priority="mandatory",
        check_mode="auto",
        crawl_field="header_has_nav",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="header_03",
        page_type="header",
        name="Ô tìm kiếm nội bộ có trong header",
        priority="high",
        check_mode="auto",
        crawl_field="header_has_search",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="header_04",
        page_type="header",
        name="CTA nổi bật (liên hệ, đặt hàng, dùng thử) trong header",
        priority="high",
        check_mode="auto",
        crawl_field="header_has_cta",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="header_05",
        page_type="header",
        name="Số điện thoại hiển thị trong header, có thể click gọi",
        priority="high",
        check_mode="auto",
        crawl_field="header_has_phone",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="header_06",
        page_type="header",
        name="Icon mạng xã hội liên kết đúng fanpage/profile",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="header_has_social_links",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="header_07",
        page_type="header",
        name="Header sticky khi scroll xuống",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="has_sticky_header",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="header_08",
        page_type="header",
        name="Hamburger menu có mặt trên mobile",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_hamburger_menu",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="header_09",
        page_type="header",
        name="Header hiển thị đúng trên mobile/tablet (responsive)",
        priority="mandatory",
        check_mode="screenshot",
        crawl_field=None,
        manual_guide="Mở trang chủ trong Chrome → F12 → Toggle device toolbar → chọn iPhone SE (375px) → chụp screenshot phần header → paste vào chat để Claude phân tích.",
        vision_prompt="This is a screenshot of a website header at 375px mobile viewport. Does the header display correctly? Check: logo is visible, navigation is collapsed or hamburger is shown, no elements overflow or overlap, text is readable. Reply JSON: {\"status\": \"passed|warning|failed\", \"evidence\": \"brief EN description\"}",
    ),
    # =========================================================
    # FOOTER (11 items — appears on every page)
    # =========================================================
    UIChecklistItem(
        id="footer_01",
        page_type="footer",
        name="Thông tin liên hệ đầy đủ (địa chỉ, SĐT, email)",
        priority="mandatory",
        check_mode="auto",
        crawl_field="footer_has_contact_info",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="footer_02",
        page_type="footer",
        name="Menu điều hướng phụ / sitemap links trong footer",
        priority="high",
        check_mode="auto",
        crawl_field="footer_has_nav_links",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="footer_03",
        page_type="footer",
        name="Icon mạng xã hội trong footer",
        priority="high",
        check_mode="auto",
        crawl_field="footer_has_social_links",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="footer_04",
        page_type="footer",
        name="Copyright, năm cập nhật tự động",
        priority="mandatory",
        check_mode="auto",
        crawl_field="footer_has_copyright",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="footer_05",
        page_type="footer",
        name="Form đăng ký nhận bản tin (newsletter)",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="footer_has_newsletter",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="footer_06",
        page_type="footer",
        name="Google Maps embed hoặc link bản đồ",
        priority="high",
        check_mode="auto",
        crawl_field="footer_has_map",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="footer_07",
        page_type="footer",
        name="Logo hiển thị trong footer",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="footer_has_logo",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="footer_08",
        page_type="footer",
        name="Link Chính sách bảo mật, Điều khoản sử dụng",
        priority="mandatory",
        check_mode="auto",
        crawl_field="footer_has_policy_links",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="footer_09",
        page_type="footer",
        name="Chứng nhận, logo thanh toán, bảo mật (nếu có)",
        priority="high",
        check_mode="auto",
        crawl_field="has_payment_logos",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="footer_10",
        page_type="footer",
        name="Footer responsive — không bị vỡ trên mobile",
        priority="mandatory",
        check_mode="screenshot",
        crawl_field=None,
        manual_guide="Mở trang chủ trong Chrome → F12 → Toggle device toolbar → chọn iPhone SE (375px) → scroll xuống cuối trang → chụp screenshot footer → paste vào chat để Claude phân tích.",
        vision_prompt="This is a screenshot of a website footer at 375px mobile viewport. Does the footer display correctly on mobile? Check: columns stack vertically, text is readable, no elements overflow horizontally, links are tappable. Reply JSON: {\"status\": \"passed|warning|failed\", \"evidence\": \"brief EN description\"}",
    ),
    UIChecklistItem(
        id="footer_11",
        page_type="footer",
        name="Giờ làm việc hiển thị (nếu là business địa phương)",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="footer_has_business_hours",
        manual_guide=None,
    ),
    # =========================================================
    # HOMEPAGE (13 items)
    # =========================================================
    UIChecklistItem(
        id="home_01",
        page_type="homepage",
        name="Banner/Hero section nổi bật, có H1 chứa từ khóa chính",
        priority="mandatory",
        check_mode="auto",
        crawl_field="headings",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="home_02",
        page_type="homepage",
        name="CTA rõ ràng trên hero section (above the fold)",
        priority="mandatory",
        check_mode="auto",
        crawl_field="hero_has_cta",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="home_03",
        page_type="homepage",
        name="Giới thiệu USP (điểm khác biệt) ngắn gọn",
        priority="high",
        check_mode="auto",
        crawl_field="has_usp_section",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="home_04",
        page_type="homepage",
        name="Section sản phẩm/dịch vụ nổi bật",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_featured_products",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="home_05",
        page_type="homepage",
        name="Testimonials / đánh giá khách hàng",
        priority="high",
        check_mode="auto",
        crawl_field="has_testimonials",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="home_06",
        page_type="homepage",
        name="Logo khách hàng / đối tác (social proof)",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="has_partner_logos",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="home_07",
        page_type="homepage",
        name="Blog/tin tức mới nhất trên trang chủ",
        priority="high",
        check_mode="auto",
        crawl_field="has_blog_section",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="home_08",
        page_type="homepage",
        name="Schema Organization/LocalBusiness đúng",
        priority="high",
        check_mode="auto",
        crawl_field="structured_data_types",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="home_09",
        page_type="homepage",
        name="Số liệu/thống kê uy tín (nếu có)",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="has_counter_stats",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="home_10",
        page_type="homepage",
        name="Popup/banner không che khuất nội dung chính",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_popup",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="home_11",
        page_type="homepage",
        name="Breadcrumb không có trên trang chủ",
        priority="high",
        check_mode="auto",
        crawl_field="has_breadcrumb_html",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="home_12",
        page_type="homepage",
        name="GTM và GA4 được tracking từ trang chủ",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_gtm",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="home_13",
        page_type="homepage",
        name="Tốc độ tải trang chủ < 3 giây trên mobile",
        priority="mandatory",
        check_mode="auto",
        crawl_field="response_time_ms",
        manual_guide=None,
    ),
    # =========================================================
    # PRODUCT CATEGORY (11 items)
    # =========================================================
    UIChecklistItem(
        id="cat_01",
        page_type="product_category",
        name="H1 chứa tên danh mục với từ khóa chính",
        priority="mandatory",
        check_mode="auto",
        crawl_field="headings",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="cat_02",
        page_type="product_category",
        name="Breadcrumb hiển thị đúng cấp bậc danh mục",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_breadcrumb_html",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="cat_03",
        page_type="product_category",
        name="Bộ lọc sản phẩm (filter) có hiện diện",
        priority="high",
        check_mode="auto",
        crawl_field="has_product_filter",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="cat_04",
        page_type="product_category",
        name="Sắp xếp sản phẩm (sort) có hiện diện",
        priority="high",
        check_mode="auto",
        crawl_field="has_product_sort",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="cat_05",
        page_type="product_category",
        name="Grid sản phẩm: ảnh, tên, giá hiển thị đủ",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_featured_products",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="cat_06",
        page_type="product_category",
        name="Phân trang hoạt động đúng",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_pagination",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="cat_07",
        page_type="product_category",
        name="Mô tả danh mục ở đầu hoặc cuối trang (SEO text)",
        priority="high",
        check_mode="auto",
        crawl_field="word_count",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="cat_08",
        page_type="product_category",
        name="Số lượng sản phẩm hiển thị rõ",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="has_product_count_display",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="cat_09",
        page_type="product_category",
        name="Danh mục con hiển thị (sub-categories)",
        priority="high",
        check_mode="auto",
        crawl_field="has_subcategory_links",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="cat_10",
        page_type="product_category",
        name="Ảnh sản phẩm load nhanh (lazy load)",
        priority="high",
        check_mode="auto",
        crawl_field="images",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="cat_11",
        page_type="product_category",
        name="Responsive — grid sản phẩm đúng trên mobile",
        priority="mandatory",
        check_mode="screenshot",
        crawl_field=None,
        manual_guide="Mở trang danh mục sản phẩm → F12 → Toggle device → iPhone SE (375px) → chụp screenshot khu vực grid sản phẩm → paste vào chat.",
        vision_prompt="This is a screenshot of a product category page at 375px mobile viewport. Does the product grid display correctly? Check: products shown in 1-2 column grid, images not distorted, product name and price visible, no horizontal overflow. Reply JSON: {\"status\": \"passed|warning|failed\", \"evidence\": \"brief EN description\"}",
    ),
    # =========================================================
    # PRODUCT DETAIL (13 items)
    # =========================================================
    UIChecklistItem(
        id="prod_01",
        page_type="product_detail",
        name="H1 là tên sản phẩm đầy đủ",
        priority="mandatory",
        check_mode="auto",
        crawl_field="headings",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="prod_02",
        page_type="product_detail",
        name="Ảnh sản phẩm có hỗ trợ zoom/lightbox",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_image_zoom",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="prod_03",
        page_type="product_detail",
        name="Giá sản phẩm hiển thị rõ ràng",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_price_display",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="prod_04",
        page_type="product_detail",
        name="Nút CTA (thêm vào giỏ, mua ngay) nổi bật",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_cart_button",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="prod_05",
        page_type="product_detail",
        name="Mô tả sản phẩm đầy đủ, có cấu trúc heading",
        priority="mandatory",
        check_mode="auto",
        crawl_field="word_count",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="prod_06",
        page_type="product_detail",
        name="Đánh giá / review của khách hàng",
        priority="high",
        check_mode="auto",
        crawl_field="has_rich_snippet_markup",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="prod_07",
        page_type="product_detail",
        name="Schema Product với đầy đủ thông tin",
        priority="high",
        check_mode="auto",
        crawl_field="structured_data_types",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="prod_08",
        page_type="product_detail",
        name="Breadcrumb đúng cấp bậc",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_breadcrumb_html",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="prod_09",
        page_type="product_detail",
        name="Tính năng chọn biến thể (size, màu) có hiện diện",
        priority="high",
        check_mode="auto",
        crawl_field="has_variant_selector",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="prod_10",
        page_type="product_detail",
        name="Thông tin vận chuyển, đổi trả rõ ràng",
        priority="high",
        check_mode="auto",
        crawl_field="has_shipping_info",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="prod_11",
        page_type="product_detail",
        name="Sản phẩm liên quan / gợi ý",
        priority="high",
        check_mode="auto",
        crawl_field="has_related_products",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="prod_12",
        page_type="product_detail",
        name="Nút chia sẻ mạng xã hội",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="has_social_share_buttons",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="prod_13",
        page_type="product_detail",
        name="Responsive — trang sản phẩm đúng trên mobile",
        priority="mandatory",
        check_mode="screenshot",
        crawl_field=None,
        manual_guide="Mở trang chi tiết sản phẩm → F12 → Toggle device → iPhone SE (375px) → chụp screenshot toàn trang (hoặc phần ảnh + giá + nút mua) → paste vào chat.",
        vision_prompt="This is a screenshot of a product detail page at 375px mobile viewport. Does the page display correctly? Check: product image visible and not distorted, price clearly shown, CTA button (add to cart/buy) is prominent and tappable, no content overflow. Reply JSON: {\"status\": \"passed|warning|failed\", \"evidence\": \"brief EN description\"}",
    ),
    # =========================================================
    # BLOG CATEGORY (12 items)
    # =========================================================
    UIChecklistItem(
        id="blog_cat_01",
        page_type="blog_category",
        name="H1 là tên danh mục blog với từ khóa",
        priority="mandatory",
        check_mode="auto",
        crawl_field="headings",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="blog_cat_02",
        page_type="blog_category",
        name="Card bài viết: ảnh thumbnail, tiêu đề, mô tả ngắn",
        priority="mandatory",
        check_mode="auto",
        crawl_field="images",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="blog_cat_03",
        page_type="blog_category",
        name="Ngày đăng bài hiển thị trên card",
        priority="high",
        check_mode="auto",
        crawl_field="has_publish_date",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="blog_cat_04",
        page_type="blog_category",
        name="Tên tác giả hiển thị trên card",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="has_author_info",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="blog_cat_05",
        page_type="blog_category",
        name="Tags / category labels trên card",
        priority="high",
        check_mode="auto",
        crawl_field="has_category_tags",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="blog_cat_06",
        page_type="blog_category",
        name="Phân trang hoạt động đúng",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_pagination",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="blog_cat_07",
        page_type="blog_category",
        name="Sidebar: bài viết phổ biến, tag cloud (nếu có)",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="has_sidebar",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="blog_cat_08",
        page_type="blog_category",
        name="Breadcrumb hiển thị đúng",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_breadcrumb_html",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="blog_cat_09",
        page_type="blog_category",
        name="Mô tả danh mục blog ngắn ở đầu trang",
        priority="high",
        check_mode="auto",
        crawl_field="word_count",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="blog_cat_10",
        page_type="blog_category",
        name="Ảnh thumbnail load nhanh, lazy load",
        priority="high",
        check_mode="auto",
        crawl_field="images",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="blog_cat_11",
        page_type="blog_category",
        name="Tìm kiếm trong blog hoạt động",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="has_search_form",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="blog_cat_12",
        page_type="blog_category",
        name="Responsive — grid bài viết đúng trên mobile",
        priority="mandatory",
        check_mode="screenshot",
        crawl_field=None,
        manual_guide="Mở trang danh mục blog/tin tức → F12 → Toggle device → iPhone SE (375px) → chụp screenshot grid bài viết → paste vào chat.",
        vision_prompt="This is a screenshot of a blog/news category page at 375px mobile viewport. Does the article grid display correctly on mobile? Check: articles shown in single column, thumbnail images not distorted, titles and dates readable, no overflow. Reply JSON: {\"status\": \"passed|warning|failed\", \"evidence\": \"brief EN description\"}",
    ),
    # =========================================================
    # BLOG POST / ARTICLE (13 items)
    # =========================================================
    UIChecklistItem(
        id="article_01",
        page_type="article",
        name="H1 là tiêu đề bài viết với từ khóa chính",
        priority="mandatory",
        check_mode="auto",
        crawl_field="headings",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="article_02",
        page_type="article",
        name="Ảnh đại diện (featured image) chất lượng cao",
        priority="mandatory",
        check_mode="auto",
        crawl_field="images",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="article_03",
        page_type="article",
        name="Tên tác giả và ảnh đại diện hiển thị",
        priority="high",
        check_mode="auto",
        crawl_field="has_author_info",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="article_04",
        page_type="article",
        name="Ngày đăng và ngày cập nhật hiển thị",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_publish_date",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="article_05",
        page_type="article",
        name="Table of Contents cho bài viết dài (>1500 từ)",
        priority="high",
        check_mode="auto",
        crawl_field="has_toc",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="article_06",
        page_type="article",
        name="Nút chia sẻ mạng xã hội (sticky hoặc cuối bài)",
        priority="high",
        check_mode="auto",
        crawl_field="has_social_share_buttons",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="article_07",
        page_type="article",
        name="Phần bình luận cuối bài viết",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="has_comment_section",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="article_08",
        page_type="article",
        name="Schema Article/BlogPosting đầy đủ",
        priority="high",
        check_mode="auto",
        crawl_field="structured_data_types",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="article_09",
        page_type="article",
        name="Breadcrumb hiển thị đúng",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_breadcrumb_html",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="article_10",
        page_type="article",
        name="Bài viết liên quan cuối trang",
        priority="high",
        check_mode="auto",
        crawl_field="has_related_posts",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="article_11",
        page_type="article",
        name="Nội dung có heading H2/H3 cấu trúc rõ ràng",
        priority="mandatory",
        check_mode="auto",
        crawl_field="headings",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="article_12",
        page_type="article",
        name="Hình ảnh trong bài có alt text và caption",
        priority="high",
        check_mode="auto",
        crawl_field="images_without_alt",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="article_13",
        page_type="article",
        name="Responsive — bài viết đọc được thoải mái trên mobile",
        priority="mandatory",
        check_mode="screenshot",
        crawl_field=None,
        manual_guide="Mở một bài viết bất kỳ → F12 → Toggle device → iPhone SE (375px) → chụp screenshot phần nội dung bài → paste vào chat.",
        vision_prompt="This is a screenshot of a blog article page at 375px mobile viewport. Is the article comfortable to read on mobile? Check: text font appears readable (not too small), content fits width without horizontal scroll, images scale properly, no layout breakage. Reply JSON: {\"status\": \"passed|warning|failed\", \"evidence\": \"brief EN description\"}",
    ),
    # =========================================================
    # ABOUT US (13 items)
    # =========================================================
    UIChecklistItem(
        id="about_01",
        page_type="about",
        name="H1 rõ ràng (Về chúng tôi / Giới thiệu công ty)",
        priority="mandatory",
        check_mode="auto",
        crawl_field="headings",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="about_02",
        page_type="about",
        name="Câu chuyện thương hiệu / lịch sử hình thành",
        priority="high",
        check_mode="auto",
        crawl_field="word_count",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="about_03",
        page_type="about",
        name="Mission / Vision / Values rõ ràng",
        priority="high",
        check_mode="auto",
        crawl_field="has_mission_text",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="about_04",
        page_type="about",
        name="Đội ngũ / Team members hiển thị",
        priority="high",
        check_mode="auto",
        crawl_field="has_team_section",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="about_05",
        page_type="about",
        name="Thống kê / số liệu ấn tượng",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="has_counter_stats",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="about_06",
        page_type="about",
        name="Chứng nhận, giải thưởng, đối tác uy tín",
        priority="high",
        check_mode="auto",
        crawl_field="has_certifications",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="about_07",
        page_type="about",
        name="Video giới thiệu công ty (nếu có)",
        priority="nicetohave",
        check_mode="auto",
        crawl_field="has_video_embed",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="about_08",
        page_type="about",
        name="Schema Organization đầy đủ",
        priority="high",
        check_mode="auto",
        crawl_field="structured_data_types",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="about_09",
        page_type="about",
        name="CTA liên hệ / tư vấn cuối trang",
        priority="high",
        check_mode="auto",
        crawl_field="has_contact_form",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="about_10",
        page_type="about",
        name="Breadcrumb đúng",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_breadcrumb_html",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="about_11",
        page_type="about",
        name="Địa chỉ văn phòng/showroom với Google Maps",
        priority="high",
        check_mode="auto",
        crawl_field="has_map_embed",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="about_12",
        page_type="about",
        name="Responsive — layout trang Về chúng tôi đúng",
        priority="mandatory",
        check_mode="screenshot",
        crawl_field=None,
        manual_guide="Mở trang Về chúng tôi → F12 → Toggle device → iPhone SE (375px) → chụp toàn trang → paste vào chat.",
        vision_prompt="This is a screenshot of an About Us page at 375px mobile viewport. Does the layout display correctly on mobile? Check: team photos not distorted, counters/stats visible, text readable, sections stack properly. Reply JSON: {\"status\": \"passed|warning|failed\", \"evidence\": \"brief EN description\"}",
    ),
    UIChecklistItem(
        id="about_13",
        page_type="about",
        name="Hình ảnh thực tế (văn phòng, team, sản xuất)",
        priority="high",
        check_mode="screenshot",
        crawl_field=None,
        manual_guide="Mở trang Về chúng tôi trên desktop → chụp screenshot phần có hình ảnh (team, văn phòng, cơ sở sản xuất) → paste vào chat để kiểm tra ảnh thực hay stock photo.",
        vision_prompt="Look at the images on this About Us page screenshot. Do the images appear to be genuine/real photos of the company (office, team, products, production facility) rather than generic stock photos? Real photos: people look natural, office/environment looks specific. Stock photos: overly polished, generic-looking people/settings. Reply JSON: {\"status\": \"passed|warning|failed\", \"evidence\": \"brief EN description\"}",
    ),
    # =========================================================
    # CONTACT (10 items)
    # =========================================================
    UIChecklistItem(
        id="contact_01",
        page_type="contact",
        name="H1 rõ ràng (Liên hệ / Tư vấn miễn phí)",
        priority="mandatory",
        check_mode="auto",
        crawl_field="headings",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="contact_02",
        page_type="contact",
        name="Form liên hệ hoạt động, validation đúng",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_contact_form",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="contact_03",
        page_type="contact",
        name="Form submit thành công → trang cảm ơn (noindex)",
        priority="high",
        check_mode="auto",
        crawl_field="has_contact_form",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="contact_04",
        page_type="contact",
        name="Số điện thoại click-to-call (tel: links)",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_phone_links",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="contact_05",
        page_type="contact",
        name="Email click-to-send (mailto: links)",
        priority="high",
        check_mode="auto",
        crawl_field="has_email_links",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="contact_06",
        page_type="contact",
        name="Google Maps embed địa chỉ chính xác",
        priority="mandatory",
        check_mode="auto",
        crawl_field="has_map_embed",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="contact_07",
        page_type="contact",
        name="Schema LocalBusiness với địa chỉ đầy đủ",
        priority="high",
        check_mode="auto",
        crawl_field="structured_data_types",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="contact_08",
        page_type="contact",
        name="Giờ làm việc hiển thị rõ ràng",
        priority="high",
        check_mode="auto",
        crawl_field="has_business_hours",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="contact_09",
        page_type="contact",
        name="Live chat hoặc Zalo/Messenger widget",
        priority="high",
        check_mode="auto",
        crawl_field="has_live_chat",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="contact_10",
        page_type="contact",
        name="Responsive — form dễ điền trên mobile",
        priority="mandatory",
        check_mode="screenshot",
        crawl_field=None,
        manual_guide="Mở trang Liên hệ → F12 → Toggle device → iPhone SE (375px) → chụp screenshot form liên hệ → paste vào chat.",
        vision_prompt="This is a screenshot of a contact page at 375px mobile viewport. Is the contact form easy to use on mobile? Check: input fields span full width, submit button is large and tappable, map (if present) fits the screen, no elements overlap. Reply JSON: {\"status\": \"passed|warning|failed\", \"evidence\": \"brief EN description\"}",
    ),
    # =========================================================
    # 404 PAGE (8 items)
    # =========================================================
    UIChecklistItem(
        id="notfound_01",
        page_type="404",
        name="Trang 404 trả về đúng HTTP status 404",
        priority="mandatory",
        check_mode="auto",
        crawl_field="status_code",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="notfound_02",
        page_type="404",
        name="Thông báo lỗi thân thiện, không phải lỗi kỹ thuật",
        priority="mandatory",
        check_mode="auto",
        crawl_field="word_count",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="notfound_03",
        page_type="404",
        name="Link về trang chủ nổi bật",
        priority="mandatory",
        check_mode="auto",
        crawl_field="internal_links",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="notfound_04",
        page_type="404",
        name="Ô tìm kiếm nội bộ trên trang 404",
        priority="high",
        check_mode="auto",
        crawl_field="has_search_form",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="notfound_05",
        page_type="404",
        name="Gợi ý trang phổ biến/liên quan",
        priority="high",
        check_mode="auto",
        crawl_field="internal_links",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="notfound_06",
        page_type="404",
        name="Trang 404 được noindex",
        priority="mandatory",
        check_mode="auto",
        crawl_field="meta_robots",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="notfound_07",
        page_type="404",
        name="Header và footer đầy đủ trên trang 404",
        priority="high",
        check_mode="auto",
        crawl_field="header_has_nav",
        manual_guide=None,
    ),
    UIChecklistItem(
        id="notfound_08",
        page_type="404",
        name="Responsive — trang 404 hiển thị đúng trên mobile",
        priority="mandatory",
        check_mode="screenshot",
        crawl_field=None,
        manual_guide="Mở trang 404 (ví dụ: domain.com/xyz-khong-ton-tai) → F12 → Toggle device → iPhone SE (375px) → chụp screenshot → paste vào chat.",
        vision_prompt="This is a screenshot of a 404 error page at 375px mobile viewport. Does the 404 page display correctly on mobile? Check: error message is readable, homepage/back button is visible and tappable, layout looks intentional (not broken). Reply JSON: {\"status\": \"passed|warning|failed\", \"evidence\": \"brief EN description\"}",
    ),
]


def get_ui_checklist_by_page_type() -> dict[str, list[UIChecklistItem]]:
    result: dict[str, list[UIChecklistItem]] = {}
    for item in UI_CHECKLIST:
        result.setdefault(item.page_type, []).append(item)
    return result


def get_ui_checklist_as_dict() -> list[dict]:
    return [
        {
            "id": item.id,
            "page_type": item.page_type,
            "name": item.name,
            "priority": item.priority,
            "check_mode": item.check_mode,
            "crawl_field": item.crawl_field,
            "manual_guide": item.manual_guide,
        }
        for item in UI_CHECKLIST
    ]
